spring:
  application:
    name: web-push

server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: geheim
    key-store-type: PKCS12
    key-alias: my-localhost
